development:
  adapter: postgresql
  encoding: unicode
  database: shopify_orders
  pool: 2
  url: <%= ENV['DATABASE_URL'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: shopify_orders
  pool: 2
  url: <%= ENV['DATABASE_URL'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: shopify_orders
  pool: 2
  url: <%= ENV['DATABASE_URL'] %>